name: Lambda Function Deployment to Send SES emails

env:
  ARTIFACT_NAME: csye6225lambda.zip
  AWS_REGION: us-east-1

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Lambda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          sudo yum update -y && 
          sudo yum install -y zip unzip
          sudo npm install crypto
          sudo npm install dotenv

      - name: Build Deployment Artifact
        run: |
          zip -r ${{ env.ARTIFACT_NAME }} index.js .env

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_ACTION_USER_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACTION_USER_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Copy Artifact to S3
        run: |
          aws s3 cp ${{ env.ARTIFACT_NAME }} s3://serverless-code-deploy-bucket/${{ env.ARTIFACT_NAME }}

      - name: Lambda function to update code
        run: |
          aws lambda update-function-code --function-name emailHandler --region us-east-1 --zip-file fileb://${{ env.ARTIFACT_NAME }}
