name: Build and Deploy Serverless on lambda function

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  SERVERLESS_ARTIFACT_NAME: csye6225-serverless-${{ github.sha }}.zip
  SERVERLESS_CODE_DEPLOY_BUCKET_NAME: serverless-code-deploy-bucket

on:
  push:
    tags:
      - '*'
    branches: [ main ]

jobs:    
  build_and_deploy:
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v1
      - name: Zippping file
        run: |
          zip -r ${{env.SERVERLESS_ARTIFACT_NAME}} *
      - name: Uploading the zip
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.SERVERLESS_ARTIFACT_NAME}}
          path: ${{ github.workspace }}/${{env.WEB_SERVER_ARTIFACT_NAME}}
        
      - uses: actions/setup-node@v2
      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_ACTION_USER_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACTION_USER_ACCESS_KEY}}
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      